### ISSUE TITLE
bazel java extractor doesn't work well with AutoValue [phab:T191]

### ISSUE THREAD

**Issue by kythe** [google/kythe#1535]
_Created by **juanch** at 2016-12-02 00:49:00_: 

My example bazel project uses AutoValue. "bazel build" works, but "bazel build --experimental_action_listener=//third_party/kythe:java_extract_kindex" reports errors below:

ERROR: /example/BUILD:1:1: Executing extra_action //third_party/kythe:java_extra_action on //:my-runner failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Exception in thread "main" com.google.devtools.kythe.extractors.shared.ExtractionException: Unable to read file content of /tmp/javac_extractor486445790337914665/com/example/AutoValue_Greeting.java
	at com.google.devtools.kythe.extractors.java.JavaCompilationUnitExtractor.processRequiredInput(JavaCompilationUnitExtractor.java:548)
	at com.google.devtools.kythe.extractors.java.JavaCompilationUnitExtractor.findRequiredFiles(JavaCompilationUnitExtractor.java:410)
	at com.google.devtools.kythe.extractors.java.JavaCompilationUnitExtractor.runJavaAnalysisToExtractCompilationDetails(JavaCompilationUnitExtractor.java:692)
	at com.google.devtools.kythe.extractors.java.JavaCompilationUnitExtractor.extract(JavaCompilationUnitExtractor.java:249)
	at com.google.devtools.kythe.extractors.java.bazel.JavaExtractor.main(JavaExtractor.java:66)

It seems the bazel extractor doesn't understand the paths of files generated by the annotation processor. I was using Kythe v21, and got the same result when using bazel java extractor from V23.

The example has bee uploaded to /google/data/rw/users/ju/juanch/bazel_autovalue_example.tar.gz.

**Comment by kythe** [comment]
revision #1592
