### ISSUE TITLE
Error in go_indexer_test.bzl [phab:T201]

### ISSUE THREAD

**Issue by kythe** [google/kythe#1607]
_Created by **asankah** at 2017-01-06 23:04:03_: 

I'm seeing this error when running bazel query:

```
ERROR: /.../kythe/kythe/go/indexer/testdata/go_indexer_test.bzl:119:23: Traceback (most recent call last):
	File "/.../kythe/kythe/go/indexer/testdata/go_indexer_test.bzl", line 106
		rule(_go_indexpack, attrs = {"library":..."), <2 more arguments>), "_goroot": attr.label(default = Label("io_bazel_rules..."))}, <2 more arguments>)
	File "/.../kythe/kythe/go/indexer/testdata/go_indexer_test.bzl", line 119, in rule
		attr.label(default = Label("//kythe/go/extr..."), <2 more arguments>)
cfg must be either 'data' or 'host'..
```

The problem turned out to be due to an older Bazel binary. Upgrading Bazel to 0.4.3 resolved the issue.

**Comment by kythe** [comment]
_**fromberger** wrote at 2017-01-06 23:43:25_:

Interesting. I can't reproduce this error. What version of Bazel are you using (e.g., `bazel info`)?

**Comment by kythe** [comment]
_**asankah** wrote at 2017-01-06 23:53:21_:

`bazel info` says

```
release: release 0.3.2-2016-10-11 (3d8ae22)
```

**Comment by kythe** [comment]
_**zarko** wrote at 2017-01-07 00:02:14_:

I've seen that on Bazels < 0.4.3. I think you'll need to update.

**Comment by kythe** [comment]
_**asankah** wrote at 2017-01-07 00:16:26_:

Indeed. I upgraded to 0.4.3. I'll close this issue. Thanks!

**Comment by kythe** [comment]
revision #1608
