### ISSUE TITLE
JsonParseException when indexing an indexpack with JavaIndexer

### ISSUE THREAD

**Issue by c-goetz** [google/kythe#21]
Hi,

I build kythe from ebce65150918046b517412f3d8e45fbd447cae90 and created some `.kindex` files from a project consisting of multiple java compilation units. Then I created an `indexpack` from these files and tried to index them with:

```
java -Xbootclasspath/p:kythe/indexers/java_indexer.jar com.google.devtools.kythe.analyzers.java.JavaIndexer --index_pack=./pack <unit-hash> > entries.proto
```

This fails with a `JsonParseException`:

```
Exception in thread "main" com.google.gson.JsonParseException: com.google.protobuf.InvalidProtocolBufferException: Missing type url when parsing: {"type_url":"kythe.io/proto/kythe.proto.JavaDetails","value":"<encoded>"}
	at com.google.devtools.kythe.util.JsonUtil$GeneratedMessageV3TypeAdapter.deserialize(JsonUtil.java:95)
	at com.google.devtools.kythe.util.JsonUtil$GeneratedMessageV3TypeAdapter.deserialize(JsonUtil.java:64)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:953)
	at com.google.gson.Gson.fromJson(Gson.java:926)
	at com.google.devtools.kythe.platform.indexpack.Archive.readUnit(Archive.java:166)
	at com.google.devtools.kythe.platform.indexpack.Archive.readUnit(Archive.java:149)
	at com.google.devtools.kythe.platform.indexpack.Archive.readDescription(Archive.java:144)
	at com.google.devtools.kythe.analyzers.java.JavaIndexer.main(JavaIndexer.java:90)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Missing type url when parsing: {"type_url":"kythe.io/proto/kythe.proto.JavaDetails","value":"<encoded>"}
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeAny(JsonFormat.java:1342)
	at com.google.protobuf.util.JsonFormat$ParserImpl.access$2000(JsonFormat.java:1116)
	at com.google.protobuf.util.JsonFormat$ParserImpl$1.merge(JsonFormat.java:1181)
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1270)
	at com.google.protobuf.util.JsonFormat$ParserImpl.parseFieldValue(JsonFormat.java:1784)
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeRepeatedField(JsonFormat.java:1523)
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeField(JsonFormat.java:1481)
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1315)
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1273)
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1155)
	at com.google.protobuf.util.JsonFormat$Parser.merge(JsonFormat.java:338)
	at com.google.devtools.kythe.util.JsonUtil$GeneratedMessageV3TypeAdapter.deserialize(JsonUtil.java:89)
	... 9 more
```

After some research in gunzipped the `unit` file, replaced `type_url` with `@type` and gzipped it again.

This leaves me with:
```
Exception in thread "main" com.google.gson.JsonParseException: com.google.protobuf.InvalidProtocolBufferException: Cannot resolve type: kythe.io/proto/com.google.devtools.kythe.proto.JavaDetails
	at com.google.devtools.kythe.util.JsonUtil$GeneratedMessageV3TypeAdapter.deserialize(JsonUtil.java:95)
	at com.google.devtools.kythe.util.JsonUtil$GeneratedMessageV3TypeAdapter.deserialize(JsonUtil.java:64)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:953)
	at com.google.gson.Gson.fromJson(Gson.java:926)
	at com.google.devtools.kythe.platform.indexpack.Archive.readUnit(Archive.java:166)
	at com.google.devtools.kythe.platform.indexpack.Archive.readUnit(Archive.java:149)
	at com.google.devtools.kythe.platform.indexpack.Archive.readDescription(Archive.java:144)
	at com.google.devtools.kythe.analyzers.java.JavaIndexer.main(JavaIndexer.java:90)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Cannot resolve type: kythe.io/proto/com.google.devtools.kythe.proto.JavaDetails
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeAny(JsonFormat.java:1347)
	at com.google.protobuf.util.JsonFormat$ParserImpl.access$2000(JsonFormat.java:1116)
	at com.google.protobuf.util.JsonFormat$ParserImpl$1.merge(JsonFormat.java:1181)
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1270)
	at com.google.protobuf.util.JsonFormat$ParserImpl.parseFieldValue(JsonFormat.java:1784)
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeRepeatedField(JsonFormat.java:1523)
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeField(JsonFormat.java:1481)
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1315)
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1273)
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1155)
	at com.google.protobuf.util.JsonFormat$Parser.merge(JsonFormat.java:338)
	at com.google.devtools.kythe.util.JsonUtil$GeneratedMessageV3TypeAdapter.deserialize(JsonUtil.java:89)
	... 9 more
```

I am not sure what to do now. Could you point me towards a solution?

Thanks and have a nice day,
Carlo

**Comment by schroederc** [comment]
https://phabricator-dot-kythe-repo.appspot.com/D2321 should address this issue.  Let me know if it works for you by either patching it locally or pulling the change down once it is submitted.

**Comment by schroederc** [comment]
Once you pull in 53fdfe5, you will need to rebuild your tools and reconstruct your indexpack.  The Java indexer should work then.

**Comment by c-goetz** [comment]
This fixed the exceptions.
Thanks!
