### ISSUE TITLE
Support java_verifier_test.load_plugin when the plugin has deps that must also be on the classpath.

Without this, the indexer will throw a NoClassDefFoundException at runtime when the ClassLoader attempts to load one of the classes that the... [phab:D2009]

### ISSUE THREAD

**Issue by kythe** [google/kythe#2464]
_Created by **ronshapiro** at 2017-11-02 15:59:14_: 

...plugin depends on.

**Comment by kythe** [comment]
_**schroederc** accepted this revision at 2017-11-02 17:08:40_

**Comment by kythe** [comment]
_**schroederc** closed via commit 7f8950c9469980477906dace5f3d48c788e5835b at 2017-11-02 17:08:52_

**Comment by kythe** [comment]
_**bzz** wrote at 2017-11-09 17:29:54_:

Sorry for digging this up, but seems like at least on macOS

```
bazel build --verbose_failures //kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg:definitions_tests
```

results in 

```
NFO: Found 1 target...
INFO: From IndexCompilation kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/definitions_tests_entriesdefinitions_tests_kindex.kindex.entries:
Exception in thread "main" java.lang.NoClassDefFoundError: com/beust/jcommander/JCommander
	at com.google.devtools.kythe.analyzers.base.IndexerConfig.parseCommandLine(IndexerConfig.java:58)
	at com.google.devtools.kythe.analyzers.java.JavaIndexer.main(JavaIndexer.java:47)
Caused by: java.lang.ClassNotFoundException: com.beust.jcommander.JCommander
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

ERROR: /xxx/kythe/kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD:34:1: output 'kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/definitions_tests_entriesdefinitions_tests_kindex.kindex.entries' was not created.
ERROR: /xxx/kythe/kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD:34:1: not all outputs were created or valid.
Target //kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg:definitions_tests failed to build
INFO: Elapsed time: 0.739s, Critical Path: 0.37s
```

**Comment by kythe** [comment]
_**ronshapiro** wrote at 2017-11-09 17:31:43_:

>>! In (earlier comment), bzz wrote:
> Sorry for digging this up, but seems like at least on macOS
> 
> ```
> bazel build --verbose_failures //kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg:definitions_tests
> ```
> 
> results in 
> 
> ```
> NFO: Found 1 target...
> INFO: From IndexCompilation kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/definitions_tests_entriesdefinitions_tests_kindex.kindex.entries:
> Exception in thread "main" java.lang.NoClassDefFoundError: com/beust/jcommander/JCommander
> 	at com.google.devtools.kythe.analyzers.base.IndexerConfig.parseCommandLine(IndexerConfig.java:58)
> 	at com.google.devtools.kythe.analyzers.java.JavaIndexer.main(JavaIndexer.java:47)
> Caused by: java.lang.ClassNotFoundException: com.beust.jcommander.JCommander
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 2 more
> 
> ERROR: /xxx/kythe/kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD:34:1: output 'kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/definitions_tests_entriesdefinitions_tests_kindex.kindex.entries' was not created.
> ERROR: /xxx/kythe/kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD:34:1: not all outputs were created or valid.
> Target //kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg:definitions_tests failed to build
> INFO: Elapsed time: 0.739s, Critical Path: 0.37s
> ```

Run `bazel clean --expunge`. Apparently there was some issues where bazel can't release to update something (it might have been from the commit to update all the deps versions). That fixed it for me and a few other people.

**Comment by kythe** [comment]
_**bzz** wrote at 2017-11-12 21:01:37_:

>>! In (earlier comment), ronshapiro wrote:
>>>! In (earlier comment), bzz wrote:
>> Sorry for digging this up, but seems like at least on macOS
>> 
>> ```
>> bazel build --verbose_failures //kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg:definitions_tests
>> ```
>> 
>> results in 
>> 
>> ```
>> NFO: Found 1 target...
>> INFO: From IndexCompilation kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/definitions_tests_entriesdefinitions_tests_kindex.kindex.entries:
>> Exception in thread "main" java.lang.NoClassDefFoundError: com/beust/jcommander/JCommander
>> 	at > 
>> ...
> Run `bazel clean --expunge`. Apparently there was some issues where bazel can't release to update something (it might have been from the commit to update all the deps versions). That fixed it for me and a few other people.

Thank you very much for prompt response. Indeed, that does the trick.
