### ISSUE TITLE
Build failure on macOS under bazel 0.9.0 [phab:T288]

### ISSUE THREAD

**Issue by kythe** [google/kythe#2605]
_Created by **fromberger** at 2018-01-25 01:41:30_: 

Per benjyw in https://groups.google.com/d/msg/kythe-dev/8yI70zddW5M/GGSKh_R7AAAJ, the build on macOS with Bazel 0.9.0 and a clean repo is failing with this error:

```
ERROR: /Users/benjyw/src/kythe/kythe/web/ui/BUILD:9:1: Executing genrule //kythe/web/ui:prod-js failed (Exit 1)
Exception in thread "main" java.lang.ExceptionInInitializerError
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:375)
at clojure.lang.RT.loadClassForName(RT.java:2093)
at clojure.lang.RT.load(RT.java:430)
at clojure.lang.RT.load(RT.java:411)
at clojure.core$load$fn__5066.invoke(core.clj:5641)
at clojure.core$load.doInvoke(core.clj:5640)
at clojure.lang.RestFn.invoke(RestFn.java:408)
at clojure.core__init.load(Unknown Source)
at clojure.core__init.<clinit>(Unknown Source)
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:375)
at clojure.lang.RT.loadClassForName(RT.java:2093)
at clojure.lang.RT.load(RT.java:430)
at clojure.lang.RT.load(RT.java:411)
at clojure.lang.RT.doInit(RT.java:447)
at clojure.lang.RT.<clinit>(RT.java:329)
at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.ClassNotFoundException: java/sql/Timestamp
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:292)
at clojure.instant__init.__init0(Unknown Source)
at clojure.instant__init.<clinit>(Unknown Source)
... 18 more
Target //kythe/release:release failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 504.892s, Critical Path: 50.97s
```

**Comment by kythe** [comment]
_**salguarnieri** wrote at 2018-01-25 01:45:59_:

It sounds like the problem is with java 9 modules. On my machine (high sierra, bazel 0.9, kythe head), I can build //kythe/release.

**Comment by kythe** [comment]
_**fromberger** wrote at 2018-01-25 01:53:27_:

Update from benjyw:

> Looks like it's actually a JDK 9 issue. I have that installed on my system, but set JAVA_HOME to point to JDK 8 until I can iron out all the 9-related issues (of which, it turns out, there are many).  However bazel, apparently, doesn't respect JAVA_HOME and somehow finds JDK 9 anyway... Not sure if this would also be the case on Linux?
>
> Anyway, removing JDK 9 from my system entirely got the build to pass. 

This sounds like the inverse of the issue I hit recently with zlib, except there it //was// using the ambient installation whereas here it seems to be ignoring it. I wonder if the WORKSPACE file can override that.

**Comment by kythe** [comment]
_**benjyw** wrote at 2018-01-25 02:27:46_:

If there's a way to lock down the JVM version to 8 in the WORKSPACE, sounds like the right thing to do until things work with 9.

**Comment by kythe** [comment]
_**schroederc** wrote at 2018-01-26 23:15:45_:

There's a lot info for Bazel+JDK9 in https://github.com/bazelbuild/bazel/issues/3410 and https://github.com/bazelbuild/bazel/issues/428.  Short story is that neither Bazel nor Kythe supports building with JDK9, and I don't think there's an easy way of locking down the Java version in our config so we can't do anything.
