### ISSUE TITLE
Support Bazel v0.14.0

### ISSUE THREAD

**Issue by schroederc** [google/kythe#80]
Build failure when using Bazel v0.14.0:

```
Traceback (most recent call last):
        File "/usr/local/google/home/schroederc/kythe/kythe/cxx/extractor/testdata/BUILD", line 238
                cc_extract_kindex(name = 'extract_verify_std_string_test_kindex')
        File "/usr/local/google/home/schroederc/kythe/tools/build_rules/verifier_test/cc_indexer_test.bzl", line 102, in _cc_extract_kindex_impl
                depset([extract(ctx = ctx, kindex = get...])
        File "/usr/local/google/home/schroederc/kythe/tools/build_rules/verifier_test/cc_indexer_test.bzl", line 103, in depset
                extract(ctx = ctx, kindex = getattr(ctx.ou...), <5 more arguments>)
        File "/usr/local/google/home/schroederc/kythe/tools/build_rules/verifier_test/cc_indexer_test.bzl", line 109, in extract
                _compiler_options(cpp)
        File "/usr/local/google/home/schroederc/kythe/tools/build_rules/verifier_test/cc_indexer_test.bzl", line 57, in _compiler_options
                cpp.compiler_options([])
struct has no method 'compiler_options'
```

**Comment by creachadair** [comment]
I believe @shahms was working on this, but in short Bazel changed the way the C++ toolchains work, and we'll have to fix our rules before we can use 0.14.0.

**Comment by schroederc** [comment]
https://github.com/google/kythe/pull/37 was supposed to prepare for this but is actually the cause of the breakage.

**Comment by creachadair** [comment]
Should we revert #37 for now, then?

**Comment by schroederc** [comment]
No.

**Comment by danielmoy-google** [comment]
Unclear if this is related to .14, but I have a separate clean clone that simply modifies to accept bazel .14.0, and get this error:

$ bazel build kythe/...
ERROR: /usr/local/google/home/danielmoy/code/cleankythe/kythe/java/com/google/devtools/kythe/common/BUILD:3:1: no such package '@com_google_common_flogger//api': Error cloning repository: git@github.com:google/flogger: Auth fail caused by git@github.com:google/flogger: Auth fail caused by Auth fail and referenced by '//kythe/java/com/google/devtools/kythe/common:flogger'
