### ISSUE TITLE
Error in kythe.bzl: cc_verifier_test_impl [phab:T80]

### ISSUE THREAD

**Issue by kythe** [google/kythe#875]
_Created by **fromberger** at 2015-11-25 16:49:01_: 

Repro:
```
$ bazel build //kythe/cxx/extractor/testdata:extract_verify_std_string_test
ERROR: $PWD/kythe/kythe/cxx/extractor/testdata/BUILD:134:1: in cc_verifier_test rule //kythe/cxx/extractor/testdata:extract_verify_std_string_test: 
Traceback (most recent call last):
        File "$PWD/kythe/kythe/cxx/extractor/testdata/BUILD", line 134
                cc_verifier_test(name = 'extract_verify_std_string_test')
        File "$PWD/kythe/tools/build_rules/kythe.bzl", line 115, in cc_verifier_test_impl
                extract(ctx, kindex, args, inputs = [src], mnemo...')
        File "$PWD/kythe/tools/build_rules/kythe.bzl", line 2, in extract
                ctx.resolve_command(tools = [ctx.attr._extractor])
Type ctx has no function resolve_command().
ERROR: Analysis of target '//kythe/cxx/extractor/testdata:extract_verify_std_string_test' failed; build aborted.
INFO: Elapsed time: 0.742s
```

Version:
```
$ bazel version
Build label: head (8c353e4)
Build target: bazel-out/local_linux-fastbuild/bin/src/main/java/bazel-main_deploy.jar
Build time: Wed Oct 7 19:03:24 2015 (1444244604)
Build timestamp: 1444244604
Build timestamp as int: 1444244604
```

It is quite possible I'm using a bad bazel commit, though this was working for me at the end of last week.

**Comment by kythe** [comment]
_**zarko** wrote at 2015-11-25 20:55:06_:

I'm at f87a414a6bf50613a2c419e53a96f76154f44ae3, which is more recent than 8c353e4. Looks like resolve_command was added in 79be96fcf; that commit is slightly newer than 8c353e4. Maybe last week you were using a different Bazel binary?

**Comment by kythe** [comment]
_**fromberger** wrote at 2015-11-25 21:09:12_:

Ah, yes, that helps, thanks. It works when I rebuild Bazel at commit `f87a414a6bf50613a2c419e53a96f76154f44ae3`.

We still need to figure out a more satisfactory way to deal with the tool changes, but that isn't for this task.
