### ISSUE TITLE
NPE in javac_extractor [phab:T82]

### ISSUE THREAD

**Issue by kythe** [google/kythe#880]
_Created by **aandryashin** at 2015-12-01 17:41:00_: 

Hello!

There is an issue when provide sources list via files using space bar as separator instead of new line. Here are steps to reproduce the issue:

```
$ cat > One.java << EOF
public class One {
}
EOF
```

```
$ cat > Two.java << EOF
public class Two {
}
EOF
```

```
$ echo One.java Two.java > file.list
```

```
$ ls
One.java  Two.java  file.list
```

```
$ export KYTHE_ROOT_DIRECTORY="$PWD"
```

```
$ java -jar /opt/kythe/extractors/javac_extractor.jar file.list
Unexpected error compiling and indexing java compilation: java.lang.NullPointerException
java.lang.NullPointerException
	at com.sun.tools.javac.main.Main.warning(Main.java:195)
	at com.sun.tools.javac.main.Main.error(Main.java:188)
	at com.sun.tools.javac.main.Main$1.error(Main.java:140)
	at com.sun.tools.javac.main.Option$27.process(Option.java:465)
	at com.sun.tools.javac.main.Main.processArgs(Main.java:260)
	at com.sun.tools.javac.main.Main.processArgs(Main.java:221)
	at com.google.devtools.kythe.extractors.java.standalone.Javac8Wrapper.processCompilation(Javac8Wrapper.java:52)
	at com.google.devtools.kythe.extractors.java.standalone.AbstractJavacWrapper.process(AbstractJavacWrapper.java:90)
	at com.google.devtools.kythe.extractors.java.standalone.Javac8Wrapper.main(Javac8Wrapper.java:114)
```

By the way javac works fine with this format.

**Comment by kythe** [comment]
commit 808a6c2e0623b7cdf7451b6b98a660b6d0a4510f

**Comment by kythe** [comment]
revision #895
