### ISSUE TITLE
exception when javac wrapper is used together with annotation processors [phab:T83]

### ISSUE THREAD

**Issue by kythe** [google/kythe#881]
_Created by **juanch** at 2015-12-01 18:46:50_: 

**Java project**: https://github.com/eclipse/vert.x

**pom.xml** contains:

<plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <executions>
            <execution>
              <id>default-compile</id>
              <configuration>
                <annotationProcessors>
                  <annotationProcessor>io.vertx.docgen.JavaDocGenProcessor</annotationProcessor>
                  <annotationProcessor>io.vertx.codegen.CodeGenProcessor</annotationProcessor>
                </annotationProcessors>
                <compilerArgs>
                  <arg>-Adocgen.output=${asciidoc.dir}/java</arg>
                  <arg>-AoutputDirectory=${project.basedir}/src/main</arg>
                  <arg>-Amaven.groupId=${project.groupId}</arg>
                  <arg>-Amaven.artifactId=${project.artifactId}</arg>
                  <arg>-Amaven.version=${project.version}</arg>
                </compilerArgs>
                <generatedSourcesDirectory>${generated.dir}</generatedSourcesDirectory>
              </configuration>
            </execution>
            <execution>
              <id>default-testCompile</id>
              <configuration>
                <annotationProcessors>
                  <annotationProcessor>io.vertx.codegen.CodeGenProcessor</annotationProcessor>
                </annotationProcessors>
                <compilerArgs>
                  <arg>-AoutputDirectory=${project.basedir}/src/test</arg>
                </compilerArgs>
              </configuration>
            </execution>
          </executions>
        </plugin>

**command to compile**: mvn install clean -DskipTests=true -Dmaven.compiler.forceJavacCompilerUse=true -Dmaven.compiler.fork=true -Dmaven.compiler.executable=/opt/kythe/extractors/javac-wrapper.sh

The command succeeded but no index data generated.

**javac-extractor.err**:
Unexpected error compiling and indexing java compilation: com.google.devtools.kythe.extractors.shared.ExtractionException: Bad processor entry
com.google.devtools.kythe.extractors.shared.ExtractionException: Bad processor entry
	at com.google.devtools.kythe.extractors.java.JavaCompilationUnitExtractor.runJavaAnalysisToExtractCompilationDetails(JavaCompilationUnitExtractor.java:611)
	at com.google.devtools.kythe.extractors.java.JavaCompilationUnitExtractor.extract(JavaCompilationUnitExtractor.java:243)
	at com.google.devtools.kythe.extractors.java.standalone.Javac8Wrapper.processCompilation(Javac8Wrapper.java:97)
	at com.google.devtools.kythe.extractors.java.standalone.AbstractJavacWrapper.process(AbstractJavacWrapper.java:90)
	at com.google.devtools.kythe.extractors.java.standalone.Javac8Wrapper.main(Javac8Wrapper.java:114)
Caused by: java.lang.ClassNotFoundException: io.vertx.docgen.JavaDocGenProcessor,io.vertx.codegen.CodeGenProcessor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.google.devtools.kythe.extractors.java.JavaCompilationUnitExtractor.runJavaAnalysisToExtractCompilationDetails(JavaCompilationUnitExtractor.java:609)
	... 4 more

Unexpected error compiling and indexing java compilation: com.google.devtools.kythe.extractors.shared.ExtractionException: Bad processor entry
com.google.devtools.kythe.extractors.shared.ExtractionException: Bad processor entry
	at com.google.devtools.kythe.extractors.java.JavaCompilationUnitExtractor.runJavaAnalysisToExtractCompilationDetails(JavaCompilationUnitExtractor.java:611)
	at com.google.devtools.kythe.extractors.java.JavaCompilationUnitExtractor.extract(JavaCompilationUnitExtractor.java:243)
	at com.google.devtools.kythe.extractors.java.standalone.Javac8Wrapper.processCompilation(Javac8Wrapper.java:97)
	at com.google.devtools.kythe.extractors.java.standalone.AbstractJavacWrapper.process(AbstractJavacWrapper.java:90)
	at com.google.devtools.kythe.extractors.java.standalone.Javac8Wrapper.main(Javac8Wrapper.java:114)
Caused by: java.lang.ClassNotFoundException: io.vertx.codegen.CodeGenProcessor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.google.devtools.kythe.extractors.java.JavaCompilationUnitExtractor.runJavaAnalysisToExtractCompilationDetails(JavaCompilationUnitExtractor.java:609)
	... 4 more

**Comment by kythe** [comment]
commit ad5bdcad1d4a57e54c11aec82422ccf3d0445525

**Comment by kythe** [comment]
revision #894
